### ISSUE TITLE
Bug in warning threshold detection with the check_kafka.py plugin

### ISSUE THREAD

**Issue by rendicott** [HariSekhon/pylib#1]
I hit a strange bug with the check_kafka.py script when the kafka publish and consume takes longer than the warning threshold (1 second) it overrides the NagiosPlugin object's self.warning() method and sets it as an integer of 1. For now I just modified check_kafka.py to have much higher default thresholds. 

The error shows up as an UNKNOWN response from the plugin with the message "UNKNOWN: 'int' object is not callable "

![image](https://cloud.githubusercontent.com/assets/6463983/20308281/2480bdee-ab11-11e6-816e-88e248286c60.png)

I added some debug print messages in check_kafka.py, then in pubsub_nagiosplugin.py, and finally in nagiosplugin.py. I think the bug is somewhere in the threshold checking mechanisms in nagiosplugin.py. 

```
[root@ap-bornge02 pylib]# python /opt/nagios-plugins/pylib/check_kafka.py.debug --topic HealthCheckNagios
Returning
checking consumed message 'Test message from Hari Sekhon check_kafka.py.debug on host ap-bornge02.docl.nic at epoch 1479217115.2 (Tue Nov 15 08:38:35 2016) with random token 'ZD55usdANyDRfJ8LCEvv'' == published message 'Test message from Hari Sekhon check_kafka.py.debug on host ap-bornge02.docl.nic at epoch 1479217115.2 (Tue Nov 15 08:38:35 2016) with random token 'ZD55usdANyDRfJ8LCEvv''
checking self._consumed_message is not equal to self.publish_message....
setting self.message to my name or something
appending to self.msg with some time crap
running self.check_thresholds().....
Do I even have a val for self._publish_time? = 1.268
Calling self.get_threshold()...
checking self.warning() or self.critica().....
Calling self.get_threshold()...
checking self.warning() or self.critica().....
Warning in name so calling self.warning().....
type of self.warning = '1'
UNKNOWN: 'int' object is not callable
```

**Comment by HariSekhon** [comment]
Hi @rendicott 

Thanks very much for raising this issue. If you re-run the program with triple verbose mode ```-vvv``` you'll get more debug output including a traceback which will help narrow down the error.

If you can paste that debug output in to this ticket I'll have a look and see if we can do a quick fix.

Thanks

Hari

**Comment by rendicott** [comment]
I set the warning threshold back to 1 and ran it with -vvv
Here's the trace:
```
[root@ap-bornge02 pylib]# python /opt/nagios-plugins/pylib/check_kafka.py --topic HealthCheckNagios -vvv
2016-11-15 11:14:15,816 - cli.py[main:152](21687) - INFO  - verbose level: 3 (DEBUG)
2016-11-15 11:14:15,817 - utils.py[log_option:2098](21687) - INFO  - timeout:  10
2016-11-15 11:14:15,817 - cli.py[main:155](21687) - DEBUG - setting timeout alarm (10)
2016-11-15 11:14:15,817 - utils.py[log_option:2098](21687) - INFO  - brokers:  localhost:9092
2016-11-15 11:14:15,818 - utils.py[log_option:2098](21687) - INFO  - topic:  HealthCheckNagios
2016-11-15 11:14:15,819 - utils.py[log_option:2098](21687) - INFO  - partition:  0
2016-11-15 11:14:15,819 - utils.py[log_option:2098](21687) - INFO  - acks:  1
2016-11-15 11:14:15,819 - threshold.py[__init__:50](21687) - DEBUG - warning threshold simple = upper
2016-11-15 11:14:15,819 - threshold.py[__init__:51](21687) - DEBUG - warning threshold positive = True
2016-11-15 11:14:15,820 - threshold.py[__init__:52](21687) - DEBUG - warning threshold integer = True
2016-11-15 11:14:15,820 - threshold.py[__init__:53](21687) - DEBUG - warning threshold min = None
2016-11-15 11:14:15,820 - threshold.py[__init__:54](21687) - DEBUG - warning threshold max = None
2016-11-15 11:14:15,820 - threshold.py[__parse_threshold__:72](21687) - DEBUG - warning threshold given = '1'
2016-11-15 11:14:15,822 - threshold.py[__parse_threshold__:106](21687) - DEBUG - warning threshold upper boundary = 1.0
2016-11-15 11:14:15,822 - threshold.py[__parse_threshold__:107](21687) - DEBUG - warning threshold lower boundary = None
2016-11-15 11:14:15,823 - utils.py[log_option:2098](21687) - INFO  - warning:  1
2016-11-15 11:14:15,823 - threshold.py[__init__:50](21687) - DEBUG - critical threshold simple = upper
2016-11-15 11:14:15,823 - threshold.py[__init__:51](21687) - DEBUG - critical threshold positive = True
2016-11-15 11:14:15,823 - threshold.py[__init__:52](21687) - DEBUG - critical threshold integer = True
2016-11-15 11:14:15,824 - threshold.py[__init__:53](21687) - DEBUG - critical threshold min = None
2016-11-15 11:14:15,824 - threshold.py[__init__:54](21687) - DEBUG - critical threshold max = None
2016-11-15 11:14:15,824 - threshold.py[__parse_threshold__:72](21687) - DEBUG - critical threshold given = '10'
2016-11-15 11:14:15,824 - threshold.py[__parse_threshold__:106](21687) - DEBUG - critical threshold upper boundary = 10.0
2016-11-15 11:14:15,824 - threshold.py[__parse_threshold__:107](21687) - DEBUG - critical threshold lower boundary = None
2016-11-15 11:14:15,831 - utils.py[log_option:2098](21687) - INFO  - critical:  10
2016-11-15 11:14:15,831 - pubsub_nagiosplugin.py[run:101](21687) - INFO  - subscribing
2016-11-15 11:14:17,246 - check_kafka.py[subscribe:216](21687) - DEBUG - partition assignments: set([])
2016-11-15 11:14:17,246 - check_kafka.py[subscribe:222](21687) - DEBUG - assigning partition 0 to consumer
2016-11-15 11:14:17,246 - check_kafka.py[subscribe:225](21687) - DEBUG - partition assignments: set([TopicPartition(topic='HealthCheckNagios', partition=0)])
2016-11-15 11:14:17,246 - check_kafka.py[subscribe:227](21687) - DEBUG - getting current offset
2016-11-15 11:14:17,516 - check_kafka.py[subscribe:235](21687) - DEBUG - recorded starting offset '56565'
2016-11-15 11:14:17,517 - pubsub_nagiosplugin.py[run:103](21687) - INFO  - publishing message 'Test message from Hari Sekhon check_kafka.py on host ap-bornge02.docl.nic at epoch 1479226455.81 (Tue Nov 15 11:14:15 2016) with random token 'xdRJsWUM8XJfYjsDEcaI''
2016-11-15 11:14:17,517 - check_kafka.py[publish:239](21687) - DEBUG - creating producer
2016-11-15 11:14:18,588 - check_kafka.py[publish:250](21687) - DEBUG - producer.send()
2016-11-15 11:14:18,590 - check_kafka.py[publish:257](21687) - DEBUG - producer.flush()
2016-11-15 11:14:18,619 - pubsub_nagiosplugin.py[run:108](21687) - INFO  - published in 1.102 secs
2016-11-15 11:14:18,619 - check_kafka.py[consume:262](21687) - DEBUG - consumer.seek(56565)
2016-11-15 11:14:18,620 - check_kafka.py[consume:265](21687) - DEBUG - consumer.poll(timeout_ms=4500.0)
2016-11-15 11:14:18,631 - check_kafka.py[consume:267](21687) - DEBUG - msg object returned: {TopicPartition(topic=u'HealthCheckNagios', partition=0): [ConsumerRecord(topic=u'HealthCheckNagios', partition=0, offset=56565, timestamp=1479226458589, timestamp_type=0, key='check_kafka.py-z58rMFwQLJZ2ZEu7nO6a', value="Test message from Hari Sekhon check_kafka.py on host ap-bornge02.docl.nic at epoch 1479226455.81 (Tue Nov 15 11:14:15 2016) with random token 'xdRJsWUM8XJfYjsDEcaI'", checksum=-74465764, serialized_key_size=35, serialized_value_size=164)]}
2016-11-15 11:14:18,632 - pubsub_nagiosplugin.py[run:113](21687) - INFO  - consumed in 0.012 secs
2016-11-15 11:14:18,632 - pubsub_nagiosplugin.py[run:114](21687) - INFO  - consumed message = 'Test message from Hari Sekhon check_kafka.py on host ap-bornge02.docl.nic at epoch 1479226455.81 (Tue Nov 15 11:14:15 2016) with random token 'xdRJsWUM8XJfYjsDEcaI''
2016-11-15 11:14:18,632 - pubsub_nagiosplugin.py[end:136](21687) - INFO  - checking consumed message 'Test message from Hari Sekhon check_kafka.py on host ap-bornge02.docl.nic at epoch 1479226455.81 (Tue Nov 15 11:14:15 2016) with random token 'xdRJsWUM8XJfYjsDEcaI'' == published message 'Test message from Hari Sekhon check_kafka.py on host ap-bornge02.docl.nic at epoch 1479226455.81 (Tue Nov 15 11:14:15 2016) with random token 'xdRJsWUM8XJfYjsDEcaI''
UNKNOWN: 'int' object is not callable

Traceback (most recent call last):
  File "/opt/nagios-plugins/pylib/harisekhon/nagiosplugin/nagiosplugin.py", line 230, in main
    super(NagiosPlugin, self).main()
  File "/opt/nagios-plugins/pylib/harisekhon/cli.py", line 171, in main
    self.__end__()
  File "/opt/nagios-plugins/pylib/harisekhon/nagiosplugin/nagiosplugin.py", line 264, in __end__
    self.end()
  File "/opt/nagios-plugins/pylib/harisekhon/nagiosplugin/pubsub_nagiosplugin.py", line 142, in end
    self.check_thresholds(self._publish_time)
  File "/opt/nagios-plugins/pylib/harisekhon/nagiosplugin/nagiosplugin.py", line 206, in check_thresholds
    threshold_breach_msg2 = self.check_threshold('{0}warning'.format(name), result)
  File "/opt/nagios-plugins/pylib/harisekhon/nagiosplugin/nagiosplugin.py", line 194, in check_threshold
    self.warning()
TypeError: 'int' object is not callable
```

**Comment by HariSekhon** [comment]
@rendicott 

Thanks that debug output really helped, I've just pushed a fix which should resolve the issue for you.

Please ```make update-no-recompile```, then try again and let me know.

**Comment by rendicott** [comment]
Thanks!
